rabbitmq:
  image: rabbitmq
  restart: always

redis:
  image: redis

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD

repository:
  build: repository/
  ports:
    - "49400:80"
  links:
    - rabbitmq
    - token
    - mysql
  environment:
    - MYSQL_ROOT_PASSWORD
    - PUB_SUB_CHANNEL

director:
  build: director/
  links:
    - rabbitmq
    - token
    - repository
  environment:
    - PUB_SUB_CHANNEL

update:
  build: update/
  links:
    - rabbitmq
  environment:
    - GIT_API_HOST
    - UPDATE_COMMAND_CHANNEL

nginxui:
  build: nginx/
  ports:
    - "49401:80"
  links:
    - ui

ui:
  build: ui/
  links:
    - repository
    - token
    - rabbitmq
  environment:
    - GH_BASIC_CLIENT_ID
    - GH_BASIC_CLIENT_SECRET
    - GIT_HOST
    - GIT_API_HOST
    - PUB_SUB_CHANNEL

scheduler:
  build: scheduler/
  ports:
    - "49402:80"
  links:
    - rabbitmq
    - mysql
  environment:
    - MYSQL_ROOT_PASSWORD
    - PUB_SUB_CHANNEL

token:
  build: tokens/
  ports:
    - "49403:80"
  links:
    - redis
    - rabbitmq
  environment:
    - TOKEN_ENCRYPTION_KEY
    - PUB_SUB_CHANNEL

documents:
  build: documents/
  links:
    - rabbitmq
    - token
    - repository
    - mysql
    - scheduler
  environment:
    - MYSQL_ROOT_PASSWORD
    - PUB_SUB_CHANNEL
