rabbitmq:
  image: rabbitmq
  restart: always

redis:
  image: redis

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD

repository:
  build: nginx/repository/
  ports:
    - "49400:80"
  links:
    - repositoryservice

repositoryservice:
  build: repository/
  links:
    - rabbitmq
    - token
    - mysql
  environment:
    - MYSQL_ROOT_PASSWORD
    - PUB_SUB_CHANNEL

director:
  build: director/
  links:
    - rabbitmq
    - token
    - repository
  environment:
    - PUB_SUB_CHANNEL

update:
  build: update/
  links:
    - rabbitmq
  environment:
    - GIT_API_HOST
    - UPDATE_COMMAND_CHANNEL

ui:
  build: nginx/ui/
  ports:
    - "49401:80"
  links:
    - uiservice

uiservice:
  build: ui/
  links:
    - repository
    - token
    - rabbitmq
  environment:
    - GH_BASIC_CLIENT_ID
    - GH_BASIC_CLIENT_SECRET
    - GIT_HOST
    - GIT_API_HOST
    - PUB_SUB_CHANNEL

scheduler:
  build: nginx/scheduler/
  ports:
    - "49402:80"
  links:
    - schedulerservice

schedulerservice:
  build: scheduler/
  links:
    - rabbitmq
    - mysql
  environment:
    - MYSQL_ROOT_PASSWORD
    - PUB_SUB_CHANNEL

token:
  build: nginx/token/
  ports:
    - "49403:80"
  links:
    - tokenservice

tokenservice:
  build: tokens/
  links:
    - redis
    - rabbitmq
  environment:
    - TOKEN_ENCRYPTION_KEY
    - PUB_SUB_CHANNEL

documents:
  build: documents/
  links:
    - rabbitmq
    - token
    - repository
    - mysql
    - scheduler
  environment:
    - MYSQL_ROOT_PASSWORD
    - PUB_SUB_CHANNEL
