rabbitmq:
   image: rabbitmq 

redis:
  image: redis

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD

repoman:
  build: repo-man/
  ports:
    - "49400:80"
  links:
    - rabbitmq
    - token
    - mysql
  environment:
    - MYSQL_ROOT_PASSWORD

update:
  build: update/
  links:
    - rabbitmq

ui:
  build: ui/
  ports:
    - "49401:80"
  links:
    - repoman
    - token
    - rabbitmq
  environment:
    - GH_BASIC_CLIENT_ID
    - GH_BASIC_CLIENT_SECRET
    - GIT_HOST
    - GIT_API_HOST

scheduler:
  build: scheduler/
  ports:
    - "49402:80"
  links:
    - rabbitmq
    - mysql
  environment:
    - MYSQL_ROOT_PASSWORD

token:
  build: tokens/
  ports:
    - "49403:80"
  links:
    - redis
    - rabbitmq
  environment:
    - TOKEN_ENCRYPTION_KEY

documents:
  build: documents/
  links:
    - rabbitmq
    - token
    - repoman
    - mysql
    - scheduler
  environment:
    - MYSQL_ROOT_PASSWORD
