rabbitmq:
   image: rabbitmq 

redis:
  image: redis

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=1234

repoman:
  build: repo-man/
  ports:
    - "49400:80"
  links:
    - redis
    - rabbitmq
    - token

ui:
  build: ui/
  ports:
    - "49401:80"
  links:
    - repoman
    - token
    - rabbitmq
  environment:
    - GH_BASIC_CLIENT_ID
    - GH_BASIC_CLIENT_SECRET

scheduler:
  build: scheduler/
  links:
    - rabbitmq
    - mysql
  environment:
    - MYSQL_ROOT_PASSWORD=1234

token:
  build: tokens/
  ports:
    - "49402:80"
  links:
    - redis
    - rabbitmq
  environment:
    - TOKEN_ENCRYPTION_KEY
